[tool.poetry]
name = "loading"
version = "0.1.0"
description = "Matrix data analysis"
authors = ["pedde-al"]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.0"
numpy = "^1.26.0"
matplotlib = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"